[[packages]]
name = "kitty"
reason = "default terminal"
category = "base"
tags = ["terminal"]

[[packages]]
name = "sxhkd"
reason = "hotkey daemon"
category = "bspwm"
tags = ["input", "system"]

[[packages]]
name = "hyprland"
reason = "window manager"
category = "hyprland"
tags = ["system", "window-manager"]

[[packages]]
name = "grim"
reason = "screenshot tool for wayland"
category = "wayland"
tags = ["screenshot", "utilities"]

[[packages]]
name = "lxappearance"
reason = "GTK theme manager"
category = "xorg"
tags = ["appearance", "customization"]
