[[packages]]
name = "aaa"
reason = "ADD DETAILS HERE"
tags = ["ADD TAGS HERE"]

[[packages]]
name = "kitty"
reason = "ADD DETAILS HERE"
tags = ["BADD TAGS HERE"]

[[packages]]
name = "alacritty"
reason = "default terminal"
tags = ["base", "terminal", "z"]

[[packages]]
name = "acpi"
reason = "for battery script"
tags = ["system", "utilities", "xase"]
